### ISSUE TITLE
Example for sharing StateMachine

### ISSUE THREAD

**Issue by tronta** [dmexe/failsafe-rs#17]
Thank you very much for this crate!
I have one question, could you please add an example how the circuit breaker is shared via multiple functions...  eg

``` rust
use failsafe::{CircuitBreaker, Config, Error};
use rand::{thread_rng, Rng};

fn dangerous_call() -> Result<(), ()> {
    if thread_rng().gen_range(0, 2) == 0 {
        return Err(());
    }
    Ok(())
}

fn caller(circuit_breaker: XXXX) {
    for n in 0..100 {
        match circuit_breaker.call(|| dangerous_call()) {
            Err(Error::Inner(_)) => {
                eprintln!("{}: fail", n);
            }
            Err(Error::Rejected) => {
                eprintln!("{}: rejected", n);
                break;
            }
            _ => {}
        }
    }
}

fn main() {
    caller(Config::new().build());
}
```
I have no clue what the type XXXX would be. Maybe others have the same issue.
Thanks a lot.

**Comment by dmexe** [comment]
Hi,

A circuit breaker instance is a trait object, one of `failsafe::CircuitBreaker` or `failsafe::futures::CurcuitBreaker`, depends on which type of circuit breaker is used (w or w/o futures).

So, the signature for `caller`'s argument:

```rust
fn caller(circuit_breaker: impl CircuitBreaker) 
```

This week I will update the crate documentation to cover this case.

**Comment by tronta** [comment]
Hmm.. I thought I have tried that as well :-(
Thanks a lot, that would be great.

**Comment by tronta** [comment]
Seems like I have a deeper misunderstanding how to utilize this crate.
I am building a web service with Actix and I'm not sure how to do it.
My current approach would be to store the circuit_breaker somewhere in a variable shared between the async functions performing the requests to the sub service.
But I'm not sure how to do that, as the says that `impl CiruitBreaker` cannot be used outside of functions...
Or do I need to extend the middleware?
Maybe do you have an example, how this is done? That would help me a lot.

**Comment by dmexe** [comment]
As I understand after looking at the `actix-web` documentation (https://actix.rs/docs/application/) you need something like this: 

```rust
use failsafe::futures::{CircuitBreaker, Config};

struct AppState<C> {
    circuit_breaker: C,
}

#[get("/")]
async fn index<C: CircuitBreaker>(data: web::Data<AppState<C>>) -> String {
    let resp = &data.circuit_breaker.call(|| ... );
    format!("{}", resp)
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new()
            .data(AppState {
                circut_breaker: Config::new().build(),
            })
            .service(index)
    })
    .bind("127.0.0.1:8080")?
    .run()
    .await
}
```

The current circuit breaker implementation has a limitation: a circuit breaker instance cannot be wrapped into a box
due to the method `call` has generic parameters. So, when a circuit breaker instance has to be stored inside a struct field, it needs an explicit generic type.

**Comment by dmexe** [comment]
Due to inactivity I'm closing the issue
