### ISSUE TITLE
Bump version number

### ISSUE THREAD

**Issue by niklasad1** [dmexe/failsafe-rs#9]
Hey,

This is commit: https://github.com/dmexe/failsafe-rs/commit/d8c6b73a98c700631385196ec2a24c1670c2214c#diff-e6580009c99953c9f2fe050c1acef12a is in my opinion sufficent to bump the version number

This will solve some resolution panics that I have received thanks

**Comment by dmexe** [comment]
There was only one change which visible to an end user, an assertion `window.as_secs() >= u64::from(slices)` was removed from WindowAdder::new. Was this a cause of an error?

**Comment by niklasad1** [comment]
Yes, this limits the time window to >= 5 seconds, because of https://github.com/dmexe/failsafe-rs/blob/master/src/failure_policy.rs#L81

If this is intended it would be good add some "documentation" to explain this!

**Comment by dmexe** [comment]
a new create version 'v0.3.0' had been published
